### ISSUE TITLE
Feature 5: Output the video feed

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#31]
# Feature Description
The vpa application should be able to output the video feed to a window that can be used for display. Furthermore, this should be able to output four copies of the video feed to a single window. (The task of rotating the video feed will come after this, *Feature 4*) 

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Consider testing strategy 
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required

**Comment by ElliotAOram** [comment]
During development of this feature I have discovered that OpenCV in python does not operate in the way in which I expected. Python OpenCV uses 3 channel (r,g,b) 2D numpy matrices as the frame for output windows. This means several changes to the design have to be made to allow for this:
* The `video_feed_array` is no longer required
  * As the output feed is only single rgb values, there is no need to separate instances of the video. Instead the values from the frame can be copied into different sections of the output window.
* `copy_video` and `populate_video_feed_array` are no longer required
  * See justification above


The changes made in Feature 3 will be rolled back before work on this issue continues. As little work has been done this branch for this issue a new branch might be created from the reverted master.

**Comment by ElliotAOram** [comment]
I have deleted my local branch and the repo branch copy and will restart this issue at the design stage

**Comment by ElliotAOram** [comment]
The `process_and_output_video` function will not be able to be tested too easily as it runs in an infinite loop that is only broken on user i/o. As such I have made the choice to refactor the functionality to a `HelperFunction` package. This should mean that this functionality should be able to be tested even if the direct output is not

**Comment by ElliotAOram** [comment]
Added in helper functions:
* `int` parsers for checking parameter (required as python has no types)
* utility functions for image positioning and display area boundaries

*These functions will be used in the `process_and_output_video` function to correctly place images*

**Comment by ElliotAOram** [comment]
Due to further refactoring the design needs to be updated
