### ISSUE TITLE
Feature 4: Scale and rotate videofeed

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#37]
# Feature Description
Where as feature 5 dealt with the placement and display of the video feed, feature 4 will rotate the video feeds so that they are all inward facing and scale the feeds to ensure that they:
 * Do not overlap
 * Fit on the screen with space for the pyramid

# Tasks

* Entry tasks:
  * Investigate how to perform rotation and scale of images in OpenCV
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [ ] Refactor where required

**Comment by ElliotAOram** [comment]
There is still one pylint variable regarding too-many-local variables in the process_and_output_video function. This should be fixed by refactoring
