### ISSUE TITLE
Feature 2: Background subtraction

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#39]
# Feature Description
This feature will remove the background from the videofeed to ensure that there is a black background for the hologram and only the foreground is of interest. 

# Tasks

* Entry tasks:
  * Spike work into how to perform background subtraction
* Design feature:
  * [ ] Consult overall model and decide if change is required
    * [ ] correct method stub for background subtraction in VideoProcessor 
* Build by feature:
  * [ ] Write tests for feature
  * [ ] Write code to pass tests
  * [ ] Refactor where required

**Comment by ElliotAOram** [comment]
simple background subtraction (`videofeed - static background image`) produces okay results and may be sufficient for a controlled environment (such as the one used for the demo).
However in order to get better colour and more consistent results it would be possible to use a MOG method but this would rely on almost constant motion and could be far more complex than required for the scenario.

I think I shall discuss this with my supervisor as it will change whether the emphasis is put on the software or the staging area.

**Comment by ElliotAOram** [comment]
Things to add in to design: 
* [ ] Use image or take new one (possibly in the constructor)
* [ ] Functionality to take new image for background - ensure there is delay to account for camera focus and light bleed
* [ ] Process background image (scale and crop)
* [ ] np.subtract(stream, background) in loop

**Comment by ElliotAOram** [comment]
Archive
