### ISSUE TITLE
Feature 6: Display menu of the application

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#42]
# Feature Description
Implement a basic app with a main menu

# Tasks

* Entry tasks:
  * Setup project
    * [x] `.gitignore`
    * [x] basic app setup
* Design feature:
  * [ ] Consult overall model and decide if change is required
  * [ ] Main Menu UI diagram
* Build by feature:
  * [ ] Write tests for feature
  * [ ] Write code to pass tests
  * [ ] Refactor where required

**Comment by ElliotAOram** [comment]
Using android studio for development
