### ISSUE TITLE
Feature 7: Implement User type

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#44]
# Feature Description
The App has activities to take you to the landing page for the Actor and the Viewer. These need to have a back end implementation that assigns a User type to that instance of the app. This will include an abstract user class, with implementations for Actor and Viewer (A new user will be created when the landing page is reached. 

This feature may also be a place to begin investigation into passing user information to a central `Game` program that handles flow (even if this is local at the moment.

# Tasks

* Design feature:
  * [ ] Consult overall model and decide if change is required
  * [ ] Consider if the Game/Core of the app should be a separate entity? 
    * Might require some research to decide - document research
* Build by feature:
  * [ ] Write tests for feature
  * [ ] Write code to pass tests
  * [ ] Refactor where required

**Comment by ElliotAOram** [comment]
This is no longer required as it is for the App rather than the website
