### ISSUE TITLE
Feature 7: Allow viewers and actors to be correctly represented

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#48]
# Feature Description
Some initial work has been done to allow the user to select either an actor or viewer. This feature will cover creating a corresponding class upon login. For the time being, just clicking the button will do this and the user will be added to a room. Once session are more closely investigated, the number of users allowed will  be limited per session.

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required
