### ISSUE TITLE
Feature 8: Select Phrase as Actor

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#50]
# Feature Description
This will involve creating the select_phrase.html page (as stated in website design). most of the code for the functionality has been implemented in the Actor class, but might require minor tweaks to create functional code.

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
  * [x] Create UI diagram
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required
