### ISSUE TITLE
Feature 10 : Session / room system 

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#54]
# Feature Description
Allow for a session to be created so that only a set number of users are able to log in to a session. The scope of the project means that only one session needs to be created. Each viewer should be able to be individually accessed. This issue should also involve investigation into how to test this (multiple selenium instances??) 

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required
