### ISSUE TITLE
Feature 13: Allow user to guess the phrase

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#60]
# Feature Description
Similar to feature 12 but allows the user to guess the full phrase not just the current word

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required
