### ISSUE TITLE
Feature 14: Inform Users when the word has been guessed correctly

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#62]
# Feature Description
The viewer and the actor must be informed when the phrase is correctly guessed. This will involve adding the second API page for `correct_guess` as stated in the design 

* [x] Waiting page
  * [x] Design
  * [x] Tests
  * [x] Implement
* [x] Create guess_correct.html API 
  * [x] Tests
  * [x] Implementation
* [x] `guess.html` and `acting.html` to poll to API for a response. 
* [x] **ALL** viewers should then be taken to a waiting page after a correct guess 
* [x] Add score to viewer interface (`guess.html`)
* [x] Update score if they were the viewer who correctly guessed

*Might be worth looking into a timer to improve scoring /points system at this stage? - possible seperate issue/feature?*

# Tasks

* Entry tasks:
  * None
* Design feature:
  * [x] Consult overall model and decide if change is required
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required

**Comment by ElliotAOram** [comment]
* Add current score to guess.html 
* Ensure test coverage for code changes
* create PR
