### ISSUE TITLE
Feature 15: Select next word as actor

### ISSUE THREAD

**Issue by ElliotAOram** [ElliotAOram/GhostPyramid#65]
# Feature Description
Allows for multi word phrases to work correctly. The points should also be updated so that the score is incremented by less for a word than it is for a phrase

# Tasks

* Entry tasks:
  * None
* Design feature:
  * *Does not require design update*
* Build by feature:
  * [x] Write tests for feature
  * [x] Write code to pass tests
  * [x] Refactor where required
